services:
  demo:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "3011:3011"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["pnpm", "run", "test"]